version: '3.3'

services:
  backend:
    build: backend/.
    ports:
      - "5001:5001" # Map container port 5000 to host port 5000
    networks:
      - default
    container_name: backend

  frontend:
    build: frontend/.
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    networks:
      - default
    env_file: ./frontend/.env.local
    depends_on:
      - 'backend'